services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../../:/workspace
    network_mode: service:db
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
